
CREATE TABLE IF NOT EXISTS USERS (
  USER_ID  BIGSERIAL PRIMARY KEY,
  USERNAME VARCHAR(255) NOT NULL,
  GENDER   CHAR(1)      NOT NULL,
  PASSWORD VARCHAR(40)  NOT NULL,
  EMAIL    VARCHAR(256) NULL,
  BIRTHDAY TIMESTAMP    NULL
);