# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:9000/users
Accepts: application/json

###

POST http://localhost:9000/users
Content-Type: application/json

{
"name":"zero",
"password":"123456",
"gender":"M",
"birthday":"1994-09-08"
}

###

GET http://localhost:9000/users/login
Accepts: application/json
Authorization: Basic emVybzoxMjM0NTY
###

GET http://localhost:9000/users/1
Accepts: application/json
Cookie: token=MTp6ZXJvOjE5MjMxMWEwNzUwNDA0MWUzYTQzMjAxNTFhZjMyYjM2ZDM5ZTMxOTA=; Path=/; HTTPOnly
###

GET http://localhost:9000/users/exists/zzzzzz
Accepts: application/json

###

GET http://localhost:9000/users/1
Accepts: application/json

###